apiVersion: ENC[AES256_GCM,data:2Mk=,iv:Ubt/C/xNiNOY3kWnKYpz1LqasMoWKKl48vluyAwUFHA=,tag:utzvhWPe3XNmTqgE6tqVcQ==,type:str]
kind: ENC[AES256_GCM,data:vQED6D8L,iv:ERA1EgaRE7qjCCo5zBV2XamzY5buPyIj/iYsrTYwoLU=,tag:XRsWoGoyNKKpavzDjhek0g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wEdZ9QFWmxiAw7p/qMa5suRwO4YhCA==,iv:mdGgYnTQW+QvCJtQD2yawNP1nxPrGYLqlGqgOKJIW9o=,tag:V8OaTIFAa4K/DOzJlLjXeQ==,type:str]
    namespace: ENC[AES256_GCM,data:UC3ehfhsft4=,iv:+YXfuGBH5T96nKMZsEkbpbyqeEEDNdQpUtgssrW6GRQ=,tag:Lph7Q3rfylOhol2V7CfQJQ==,type:str]
type: ENC[AES256_GCM,data:Ay1KfgWN,iv:+321P3Vw8ovNeLvgyd03cBrDLBNYXzmr9plDTaES66M=,tag:WijLSvLLp3Wl0r4kRPuNuA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:ZdypWhmtdQ==,iv:movkqm7NJUIvv5e9aS3E7gz6AfGuRWjL0Ooq1azRM0Y=,tag:2lB4qP+h+vijbIzlw1yxvQ==,type:str]
    password: ENC[AES256_GCM,data:910FvCpZfu7dh3yLQ4xy2LvVtI4Bj4ONwtwlzs1Xdr7yXEneHvZ8ZQh9EOMevfk2VqSmjctb1ofBWlXwQZWnmg==,iv:eEhj/RwPPv2+7WBO22rycyUu4HJBwUpkQ3vo/Pbqldg=,tag:GyCTFBJNh8YkEI86Pyh5Dg==,type:str]
    database-url: ENC[AES256_GCM,data:jriHRR2CBpx940hRwFlVOOmTVUef0irM0gF8x6DVMh4C0KHo89USecHtfH/7Cja+Qg7yEhtBnqTXJqDMPV+1Ng5NmfRXjFejAD7+r+wHnU+dRkwtQHzZhnqGAzsyYiMmiAO9VLROcR6dQoG1qGYiHz/sJpGLYNPoRG48IauTBMQ/i6re/MORWUOn8eTskthVSIsEjNKw,iv:cYxbgbJLj07yEBbpFLITfBjerzed1aVCe4O9xd7MapE=,tag:ClmeDdQvmiXTjCjvs9hA3w==,type:str]
sops:
    age:
        - recipient: age19mlxln35z0ed8mqst5llxhjggwdgkjl523zh3sx3flcynl5wepts7kc30l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRTRmTERYSUVxcUZNRlYr
            RmlXQW5ONGlyL1RMNjI0YlZCdkNWK0dTZkNrCnA4Um9MRzFuUXF3bVg2d3hrcE53
            SmpwSHNxMW5yN1ZGVG5FT3VNQTY1ZE0KLS0tIHpJNUwwclQ3eCtVK0tZK2VKUzBE
            NGRTcm5DbFl2MkwraEppcmdhU0w4dEkKRpvWKJ2cUSW8y8dHFNkFhvRvHg+RFRTu
            6EX+BS8HPYyK9XnRQnOOv36Mkj4TVA7tnYrxkYG0VdIHnS9M0bxOhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T11:20:23Z"
    mac: ENC[AES256_GCM,data:WY7dS1bqOQYpdz0lQeISA7qo2q5SJzGh/qCLJitileSVPuh2N2E+16FWsKc0CJaHLbW3IC30hC1Wdl5D+tMgGiIYXozx15zuY7MbYXdRzh/tM6ug0HEop+OWN3FBoCN9Q0eBtqClNF7W32o2IVtJvzvfVx4702prg5/FbVPTEtI=,iv:DzcJrJN3goQOIpciuAaxRX/ySM6frYgVLKkLmx4j7uo=,tag:KrvS10if0GJWC5TKxyF6MQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
