apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: books-config, namespace: media}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: homelab-media
  volumeName: media-books-config
  resources: {requests: {storage: 4Gi}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: books-library, namespace: media}
spec:
  accessModes: [ReadOnlyMany]
  storageClassName: homelab-media
  volumeName: media-books
  resources: {requests: {storage: 100Gi}}
