apiVersion: ENC[AES256_GCM,data:Z4U=,iv:vBKQ3zlKIJ44Cs7XBs8L7251gwc/4aCstkUtBfdGYPY=,tag:+tAXX75BZEikBhvnz/i/LA==,type:str]
kind: ENC[AES256_GCM,data:jlXP5XOB,iv:+h6k2t48qzMZe+9wlkrH/36yqimQAKdm1rskJqoSGGE=,tag:NnduRxVm+tVagGiaLwvq4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ll1Y1Oc6LBXE/1qEqXPCYGdEhHBS9Q==,iv:o0wq+3N9kRNnKX11cOC79DNRAbzTDDjnWX+pV94WKTE=,tag:04zdMUIPu6JXRsnPbSDZlw==,type:str]
    namespace: ENC[AES256_GCM,data:e3cJxMjL6A==,iv:F79AiC3feylUFyUAsRo/LPvHIIEAMel+K8eBO8q3wY0=,tag:kFKtaZj3UWvWp1AIfyXWEQ==,type:str]
type: ENC[AES256_GCM,data:7ZDsMaUU,iv:u9CkMc+6FwMaUFKp3GmFgflQXicpRIdTInOKjNOKQKk=,tag:73L2Lu0gTjfnK0REUnik/g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:6/U/TdlIYg==,iv:qo33g+D/gMmCcxiaiNUefS8xeQNCaN7rKrShtyXScNc=,tag:g9a6hGroJRKttHwlCZ1X6Q==,type:str]
    password: ENC[AES256_GCM,data:UvCzuFvYz95zOY7VOGpMh9JxHvREfyyFYYtwGta+KJWiZwIhnw9uLhflAGnswpd49hTy2tMaIHhOlTPtD4I8zQ==,iv:aJ7QcsP0Pl2veyyvagHT2yWyrd/I5W93Y3vs9OZ9LiI=,tag:Ve6u8WrLSNz1m0j3fHji5w==,type:str]
    database-url: ENC[AES256_GCM,data:FWnavDNTNDudm80bkavRRaL2UclGrjStdSM99ATFE0Rkza+UIHCKAOK0OXzZjwB+PLZ7IZOeP1Amh10b+ePFF5oxJTPRPy+tS1WdCapSv+yGUjRU0Tzxid5Z1+MKwt88S/iWlZKSYkKHGadpmJQqUj6PJdwnpnbc0ULMCOzXYPpMK627nRRYTNqglzpC5HQ6ZRF3kJbI,iv:14rAaqvgC8FAJO9/EjHj+IzmY7Bewh0/W8E7u97xDek=,tag:uIfJKKRQdj51OTQ9whdHuQ==,type:str]
sops:
    age:
        - recipient: age19mlxln35z0ed8mqst5llxhjggwdgkjl523zh3sx3flcynl5wepts7kc30l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcjV1K1lQRXlFdHJxOVJl
            dUZaL3BXUnFDbjJOb0dDelQrbXVpSlJPWkc0CmhDQXU3ZUFUdUVwTWh4SWI0Tjly
            MzR1SnQxbEpqMXNRTENTc21DR3UyUlEKLS0tIFRHWks3Z3hnQS9PWUJGTm8xamQ5
            SVB2ellqUUNWTkd1aTVZZ1dVOXpOV2MK09Qt7OdtJ5TqNJJ4LXMnLWoIrBUgAkgx
            ZJcSIwvef+TZxlZ/SGnyTAE/HPJqb4RRDwEaSD/oKmKU1BIvxnQzqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T11:20:23Z"
    mac: ENC[AES256_GCM,data:om/tfRBQOEXsNPJYzCHXp46faGiNUL5o5Y5r4GcklkZUVC6QD/htxffHVIYH1bvzJBq7L21sFBRCE+g37WgM07TSVUUrB2qvrX6ZNeLM+T4NK7ZkgLCzYBV15DmwSm8BnOmbOthq+ddFGuY18mJl9UNQv9LlvrcBS2V5jojwcnM=,iv:zGElGcXcUNRcoGIH2aTm2rsYoaHcYVqHVkQ4lZJ8drA=,tag:Lgs7NQN309Meddw4VS0eJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
