apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure-base.yaml
  - infrastructure-traefik.yaml
  - infrastructure-traefik-config.yaml
  - infrastructure-cert-manager.yaml
  - infrastructure-cert-manager-config.yaml
  - infrastructure-cert-manager-staging.yaml
  - infrastructure-observability.yaml
  - infrastructure-observability-config.yaml
  - apps-validation.yaml
  - phase-j.yaml
  - phase-k.yaml
