apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-jellyfin-config
spec:
  capacity: {storage: 5Gi}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homelab-media
  hostPath: {path: /srv/homelab/volumes/apps/media/jellyfin, type: DirectoryOrCreate}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{key: kubernetes.io/hostname, operator: In, values: [jamal]}]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-navidrome-config
spec:
  capacity: {storage: 2Gi}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homelab-media
  hostPath: {path: /srv/homelab/volumes/apps/media/navidrome, type: DirectoryOrCreate}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{key: kubernetes.io/hostname, operator: In, values: [jamal]}]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-config
spec:
  capacity: {storage: 4Gi}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homelab-media
  hostPath: {path: /srv/homelab/volumes/apps/media/books, type: DirectoryOrCreate}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{key: kubernetes.io/hostname, operator: In, values: [jamal]}]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies
spec:
  capacity: {storage: 100Gi}
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homelab-media
  hostPath: {path: /srv/homelab/data/movies, type: DirectoryOrCreate}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{key: kubernetes.io/hostname, operator: In, values: [jamal]}]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music
spec:
  capacity: {storage: 100Gi}
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homelab-media
  hostPath: {path: /srv/homelab/data/music, type: DirectoryOrCreate}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{key: kubernetes.io/hostname, operator: In, values: [jamal]}]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books
spec:
  capacity: {storage: 100Gi}
  accessModes: [ReadOnlyMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homelab-media
  hostPath: {path: /srv/homelab/data/books, type: DirectoryOrCreate}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions: [{key: kubernetes.io/hostname, operator: In, values: [jamal]}]
